### ISSUE TITLE
Missing libencoders.so.1 library when running binary

### ISSUE THREAD

**Issue by thekaibosh** [raspberry-pi-camera/raspindi#66]
I followed the steps on the README to run raspindi from the binary. I have a raspberry pi 4 with a fresh install of raspbian bullseye 64bit.

- ran `uname -m` and my arch is aarch64
- download libndioutput-aarch64.so into /usr/lib
- download libndi-aarch64.tar.gz and unzip into /usr/lib
- download raspindi.conf.default and mv to /etc/raspindi.conf
- download raspindi-aarch64 and mv to /usr/bin/raspindi. run chmod a+x
- run raspindi

result: 
root@camera2:/etc# raspindi
raspindi: error while loading shared libraries: libencoders.so.1: cannot open shared object file: No such file or directory

I've tried to search for a debian package that contains this file but I haven't had much luck

**Comment by jaybeeteee** [comment]
Hey Ben,
did you get this working?

**Comment by rf152** [comment]
From memory libencoders is part of ffmpeg. Have you got ffmpeg installed on the pi? (not sure what the name of the package would be, and I don't have a pi to hand at the moment)

**Comment by JanLucaB** [comment]
Hey there,
I just tested it. 

I have installed ffmpeg (`apt install ffmpeg`). I still get the error:

`raspindi-aarch64: error loading shared libraries: libencoders.so.1: cannot open shared object file: No such file or directory
`

I also had to install "libconfig++9v5" (`apt install libconfig++9v5`) because I got this error before:

`raspindi-aarch64: error loading shared libraries: libconfig++.so.9: cannot open shared object file: No such file or directory`

**Comment by XelaReko** [comment]
I am also getting the same error message and am unable to find the package that has this file. I built ffmpeg and libcamera just in case, but the file is still sadly missing.

**Comment by XelaReko** [comment]
Last update fixed this.

**Comment by rf152** [comment]
@thekaibosh Are you able to test this after the latest update please?
